// <auto-generated />
namespace NW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202005090539018_Init Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
